source "https://rubygems.org"

ruby "3.3.4"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'active_storage_validations'
gem "image_processing", "~> 1.2"
gem 'rack-cors', require: 'rack/cors'
gem 'jwt'
gem "devise"
gem "devise-jwt"
gem 'jsonapi-serializer'
gem 'pry', '~> 0.14.2'
gem 'pundit'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'rails-erd'
  gem 'rspec-rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.4'
end

group :test do
  gem 'database_cleaner-active_record'
end
